### ISSUE TITLE
Invite me to the Community 🤗

### ISSUE THREAD

**Issue by Krishnaanurag01** [https-github-com-Kushal997-das/Community-Support#13]
Please invite me to this Organisation. 

- #### Name:Anurag Krishna

- #### Github Username: 
Krishnaanurag01

- #### Discord Username(if exists): No

- #### Additional Context:
I get to know about this through Kushal sir when I was attending his session.

I want to grow along with others.

**Comment by Kushal997-das** [comment]
@Krishnaanurag01 Please check your mail .
