### ISSUE TITLE
Invite me to the Community 🤗

### ISSUE THREAD

**Issue by triposat** [https-github-com-Kushal997-das/Community-Support#19]
Please invite me to this Organisation. 

- #### Name: Satyam Tripathi 

- #### Github Username:  https://github.com/Iamtripathisatyam

- #### Discord Username(if exists): 

- #### Additional Context:  I'd want to become a member of this developer community to learn and demonstrate my abilities while also assisting the organization.

**Comment by Kushal997-das** [comment]
Check you mail .
