### ISSUE TITLE
We can include Project Guidance in that Community

### ISSUE THREAD

**Issue by SamarpanCoder2002** [https-github-com-Kushal997-das/Community-Support#2]
We are working on our latest project Project Guidance....If we include it here...I think that, That can helps to increase traffic in that organization....

Thanks @Kushal997-das

**Comment by UG-SEP** [comment]
> We are working on our latest project Project Guidance....If we include it here...I think that, That can helps to increase traffic in that organization....
> 
> Thanks @Kushal997-das

yes you are right

**Comment by SamarpanCoder2002** [comment]
> > We are working on our latest project Project Guidance....If we include it here...I think that, That can helps to increase traffic in that organization....
> > Thanks @Kushal997-das
> 
> yes you are right

Hmm...let's wait for @Kushal997-das response

**Comment by UG-SEP** [comment]
> Hmm...let's wait for @Kushal997-das response
yah

**Comment by Kushal997-das** [comment]
> We are working on our latest project Project Guidance....If we include it here...I think that, That can helps to increase traffic in that organization....
> 
> Thanks @Kushal997-das

Sure I'll add .
