### ISSUE TITLE
Wanted to become member of community

### ISSUE THREAD

**Issue by UG-SEP** [https-github-com-Kushal997-das/Community-Support#3]
Hey @Kushal997-das
Nice to hear that you started your own community i also want to become the member of Let's Learn because it let me to learn more about opensource and give a great mentor to get support..
Thanks

**Comment by Kushal997-das** [comment]
@UG-SEP Yeah sure please create an issue again !

**Comment by UG-SEP** [comment]
ok
so i have to close this issue or leave it like this

**Comment by Kushal997-das** [comment]
Close this issue and create another one .
