### ISSUE TITLE
Invite me to the Community 🤗

### ISSUE THREAD

**Issue by UG-SEP** [https-github-com-Kushal997-das/Community-Support#4]
Please invite me to this Organisation. 

- #### Name:
### _**Ujjwal**_
- #### Github Username: 
- **UG-SEP**

- #### Discord Username(if exists): 
not exist right now
- #### Additional Context:

I know about this community in my github notification

I wanted to join this community to learn more about opensource and also because i am in touch of a great mentor @Kushal997-das he let us to taught new things which help us a lot

**Comment by Kushal997-das** [comment]
Thanks for showing the interest will send you the invitation link . Check you `e-mail`

**Comment by UG-SEP** [comment]
yah accepted thanks

**Comment by Kushal997-das** [comment]
> yah accepted thanks

Don't forget after accepting to make the profile public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organization list and change the dropdown to the public: https://github.com/orgs/https-github-com-Kushal997-das/people
