### ISSUE TITLE
Invite me to the Community 🤗

### ISSUE THREAD

**Issue by SamarpanCoder2002** [https-github-com-Kushal997-das/Community-Support#5]
Please invite me to this Organisation. 

Very helpful If I became a part of that

- #### Name: Samarpan Dasgupta

- #### Github Username:  SamarpanCoder2002

- #### Discord Username(if exists): Samarpan(P)

- #### Additional Context:

From the new repo of this organization

To learn more about open source and contribute in open source

**Comment by Kushal997-das** [comment]
Send you an invitation Please check your e-mail  @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
> Send you an invitation Please check your e-mail @SamarpanCoder2002

No invitation mail came till now...please check it @Kushal997-das

**Comment by Kushal997-das** [comment]
> > Send you an invitation Please check your e-mail @SamarpanCoder2002
> 
> No invitation mail came till now...please check it @Kushal997-das

Please check this again ! check your github register mail id .

**Comment by UG-SEP** [comment]
@Kushal997-das  please close this issue this has been resolved
thanks

**Comment by SamarpanCoder2002** [comment]
Ok I closed this issue as I joined
