### ISSUE TITLE
Invite me to the Community 🤗

### ISSUE THREAD

**Issue by harshpreet0508** [https-github-com-Kushal997-das/Community-Support#7]
Please invite me to this Organisation. 

- #### Name: Harshpreet Kaur

- #### Github Username: 
https://github.com/harshpreet0508

- #### Discord Username(if exists): harshpreet0508#2400

- #### Additional Context:
LinkedIn

**Comment by Kushal997-das** [comment]
@harshpreet0508 Check your mail .
